### PR TITLE
feat: stable XAR upload and install

### PR DESCRIPTION
**Pull request by line-o**
A real breakthrough. Finally XAR installation is stable.

### CODE REVIEW

**Comment by line-o** [comment]
As stable as XAR handling currently is, see https://github.com/eXist-db/exist/issues/3598

**Review by duncdrum — COMMENTED** [review]
Looks good, although I m a bit worried about the dependency resolution, I remember some deeply broken instance in the past if a package is present but it’s dependencies can’t be found. Should we maybe perform a check if a dependency is declared, and either issue a warning, or more radically abort install of xars with dependencies?

**Comment by line-o** [comment]
@duncdrum Thanks for having a look!
 
After a lot of testing this is the only real path to break it reproducibly: https://github.com/eXist-db/exist/issues/3598

About dependency resolution and broken expath-repositories:

1. It is mentioned in the readme that dependencies will not be resolved
2. I have not seen _that_ being an issue (in stark contrast to what happens if you do not remove the old version first, which is now handled by the query).
3. automatic dependency resolution needs a public-repo url and uses other functions. This will definitely be added as separate function calls or be added here
4. The install will fail if dependencies cannot be met (see the package manager code, it is using the same functions).

**Comment by line-o** [comment]
@duncdrum I stand corrected!
I started doubting my above assumptions and yes you can install a package with a missing dependency that way.
I tested installing exist-jwt, which declares that the crypto-lib in version 1.0.0 or higher needs to be installed. 
Well, at least it can be safely updated and also removed. That is a clear indicator the expath-repo is still in OK shape after multiple of such operations.
And I also saw there is no mention of that in the readme. Will definitely add that.

**Comment by duncdrum** [comment]
@line-o did you check if you can restart the intended with the incomplete app installed? If that works we re in the clear, I seem to remember that was a big problem way back when.

**Comment by line-o** [comment]
I decided to move forward and have dependency resolution in place.
Thanks for nudging  :)

**Pull request merged**
