### PR TITLE
feat(examples): upload directory trees, apply xconf, threaded and throttled

### PR DESCRIPTION
**Pull request by line-o**
Upload directory trees into an existdb instance in parallel and throttled.
Will apply collection configurations (*.xconf) if found in the set of
files (the user connecting to the database has to be a member of the dba group for that).

`exist-upload --help` displays all options.

Examples:

```bash
spec/examples/exist-upload ~/projects/myapp /db/apps/myapp \
  --include 'collection.xconf,**/*.xml' \
  --threads 16 \
  --dry-run --verbose
```

Uploading single resource/file

```bash
spec/examples/exist-upload ~/projects/myapp/data/myfile.xml /db/apps/myapp/data \
  --dry-run --verbose
```

### CODE REVIEW

**Comment by line-o** [comment]
This new script could replace `exist-upload ` instead. Do you think this would merit a major version bump?

**Comment by line-o** [comment]
We also get to a point where adding tests for the CLI tools is necessary in order to not slow down development.

**Comment by joewiz** [comment]
@line-o Re: applying xconf files, would this make sense as a flag, disabled by default? Applying an xconf may not always be desired when uploading an xconf. Seems like this is an extra, bonus option.

**Comment by line-o** [comment]
Yes this would make sense. I thought so as well at some point and then did not do it.

**Comment by line-o** [comment]
On the other hand you can also exclude them first with --exclude "*.xconf", upload all data and then apply the configuration in a second step

**Comment by line-o** [comment]
The execution times in my testing trended towards applying the configuration first being faster, but especially with configured triggers that might be a non-option

**Comment by line-o** [comment]
exist-up will replace exist-upload

**Pull request merged**
