### PR TITLE
ci(travis): switch to docker 

### LINKED ISSUE #9: test use of docker for CI
user docker images for creating exist-db instanced and running test.
Let's see if these are faster or not

### PR DESCRIPTION
**Pull request by duncdrum**
pros: 
-   almost 50% faster
-   test against upcoming changes via `:latest` 
-   staying up to date with current and upcoming releases is fully automated

cons:
-   not calling the ci scripts to see if they work

I'd suggest to stick with major versions for backwards testing otherwise 3.6.1, release, latest.

close #9

### CODE REVIEW

**Comment by line-o** [comment]
@duncdrum looks good to me. What do you mean by 'not calling the ci scripts'?

**Comment by duncdrum** [comment]
`start-db.sh` etc. are no longer called on travis. We could delete `node-exist/ci/` here, but i m not sure if any body is using them in their own code.

**Comment by line-o** [comment]
no just remove them :)

They are only there for the build-from-source test setup and also travis specific, hence the name.

**Pull request merged**
