### PR TITLE
Expose command line scripts to package users

### PR DESCRIPTION
**Pull request by line-o**
With this applied people depending on this package should be able to run 

```
node_modules/.bin/exist-ls /db/app
```

If the package is installed globally the exposed script `exist-ls`, `exist-upload` and `exist-install` can be used everywhere in the terminal.

Tests and examples all set up their connection by requiring `spec/connection.js`. This script will default to the admin user with a blank password for comfortable testing in CI as well as when toying around on your local machine.

```
EXISTDB_SERVER=http://localhost:8080 npm test
```

dotenv-cli works with test runs, too 

```
dotenv npm test
```

:tada:

### CODE REVIEW

**Review by duncdrum — COMMENTED** [review]
would the bin commands work with `npx` ? If so, i would put these in the docs.

**Comment by line-o** [comment]
I have actually no idea. I plan to see what we get when they are packaged and I can install via npm.
I mean there is a potential for `npm i -g @existdb/node-exist && exist-install my-package.xar` to work.

**Comment by line-o** [comment]
And all this would definitely be documented ... then :)

**Comment by line-o** [comment]
Or is there a way to test that beforehand?

**Comment by line-o** [comment]
I can confirm that 
```
npm i -g @existdb/node-exist@test 
```

will expose all three command line scripts which then can be called as any other binary in the path

```
exist-ls /db/apps
```

This can then be used in conjunction with `dotenv` or similar.

I am still not sure how to tell `npx` what to do. I doubt this will work. Any pointers, @duncdrum ?

**Comment by line-o** [comment]
npx does not seem to work without @existdb/node-exist installed globally beforehand. So the npx part is obsolete.

**Comment by line-o** [comment]
I documented all changes. @duncdrum do you miss anything?
As I wrote earlier the `npx` thing does not work unless you install the package globally.
The very reason why one would want to use `npx` is to avoid having to install globally, correct?
If you agree I do not think we have to address that.

**Review by duncdrum — DISMISSED** [review]
looks good, i m not sure i agree with the sentiment about `npx` and avoid global node modules.  but thats certainly shouldn't block these changes from going in. The spice must flow

**Comment by line-o** [comment]
I was prodding and probing with better type hints when I encountered `npx -p typescript tsc` so I tried 
`npx -p @existdb/node-exist@test exist-ls` and voila! It is possible to run those command line scripts with npx but it still asks you to install the package.

**Pull request merged**
