### PR TITLE
default to https, CLI example, documentation

### PR DESCRIPTION
**Pull request by line-o**
This PR ended up being a mixed bag:
- update readme with some valuable info
- default to HTTPS 
- catch a bunch of unhandled promise rejections (which became visible due to certificate issues)
- a new CLI tool example

### CODE REVIEW

**Comment by line-o** [comment]
Oh my... the default docker does not expose the https port :(
> Error: Error: connect ECONNREFUSED 127.0.0.1:8443

**Comment by duncdrum** [comment]
Looks great nice work

**Comment by line-o** [comment]
@duncdrum do you think the configuration change should be considered a breaking change?
Then I would need to make it one ;)

**Comment by duncdrum** [comment]
Phew, good question, since old code might now raise an error, I d say yes breaking change

**Comment by line-o** [comment]
It wouldn't if the SSL certificate bundled with exist would be valid...

**Comment by duncdrum** [comment]
Sure but it’s the node-exist package, and we know there to be cert problems, would be different if it were the node-xmldb package

**Comment by line-o** [comment]
@duncdrum tempted to start that one :)

**Pull request merged**
